name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hello @${{ github.actor }}, thank you for raising an issue with us. We will get back to you ASAP."
        pr-message: "Hello @${{ github.actor }}, thank you for taking your time and effort for your contribution. We truly value it. :tada:"
